create table if not exists users
(
    id   bigint generated by default as identity,
    name varchar(255)
);

truncate table users;

-- вставка
INSERT INTO public.users (name)
VALUES ('test');

INSERT INTO public.users (name)
VALUES ('test1');

-- обновление 1
update users
set name = 'test!'
where name = 'test';

-- обновление массовое

update users
set name = 'updatedAll';

INSERT INTO public.users (name)
VALUES ('1');

-- удаление 1
delete
from users
where name = '1';

-- удаление массовое
delete
from users;

INSERT INTO public.users (name)
VALUES ('2');

-- truncate
-- удаление массовое
truncate table users;
