create table if not exists users
(
    id   bigint generated by default as identity primary key ,
    name varchar(255)
);

alter system set wal_level to 'logical';
SELECT pg_reload_conf();
SELECT version();

CREATE PUBLICATION my_pub_user FOR TABLE users WITH (publish = 'insert, update, delete');


SELECT name, setting FROM pg_settings WHERE name = 'wal_level';


truncate table users;

SELECT * FROM pg_stat_replication;

-- вставка
INSERT INTO public.users (name)
VALUES ('test');

INSERT INTO public.users (name)
VALUES ('test1');

-- обновление 1
update users
set name = 'test!'
where name = 'test';

-- обновление массовое

update users
set name = 'updatedAll';

INSERT INTO public.users (name)
VALUES ('1');

-- удаление 1
delete
from users
where name = '1';

-- удаление массовое
delete
from users;

INSERT INTO public.users (name)
VALUES ('2');

-- truncate
-- удаление массовое
truncate table users;
